sudo: false
language: clojure
lein: 2.7.1
install:
  - npm install -g karma-cli
  - npm install
  - lein deps
script:
  - ./scripts/test.sh $TEST
env:
  matrix:
  - TEST=clj
  - TEST=cljs
matrix:
  exclude:
    - env: TEST=cljs
      jdk: openjdk7
jdk:
  - oraclejdk8
node_js:
  - "8.10"
cache:
  directories:
  - "$HOME/.m2"
addons:
  chrome: stable
